name: Build go app and push to Azure on Linux
on: 
  push: 
    branches: [ main_linux ]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: Cloning repository
              uses: actions/checkout@v3

      - name: Building web app
          uses: azure/appservice-build@v3
          with:
            platform: Golang
            platform-version: 1.19
            source-directory: server
            output-directory: server/build

      # Log into Azure
      - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Deploying web app to Azure
          uses: azure/webapps-deploy@v1
          with:
            app-name: 'mizuho-go-linux'
            package: server/build



