name: Build go app and push to Linux Azure

on: 
  push: 
    branches: [ main_linux ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: jirutka/setup-alpine@v1
        with:
          branch: v3.15

      - run: cat /etc/alpine-release
        shell: alpine.sh {0}
        
      - uses: actions/checkout@v3
    
      - name: Set up  Go
        uses: actions/setup-go@v5
        with: 
          go-version: '1.20'

      - name: Build
        run: gox -osarch="linux/amd64" --output="build/app"
      
      - name: Deploy on Azure
        uses: Azure/webapps-deploy@v2
        with: 
          app-name: mizuho-go-linux
          package: build/
          publish-profile: ${{ secrets.azureWebAppLinuxPublishProfile }}
