name: Build go app and push to Azure

on: 
  push: 
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    steps: 
    - uses: actions/checkout@v3
    
    - name: Set up  Go
      uses: actions/setup-go@v3
      with: 
        go-version: 1.20

    - name: Set up Go environment
      run: |
        echo "GOPATH=C:\go" >> $GITHUB_ENV
        echo "PATH=C:\go\bin;%PATH%" >> $GITHUB_ENV
   
    - name: Install dependencies
      run: go get .
        
    - name: Build
      run: go build -o ./build/server.exe -v
    
    - name: Deploy on Azure
      uses: Azure/webapps-deploy@v2
      with: 
        app-name: mizuho-go
        package: build/
        publish-profile: ${{ secrets.azureWebAppPublishProfile }}
